[lint]
select = ["ALL"]
ignore = [
    "COM812", # Checks for the absence of trailing commas
    "COM819", # Checks for the presence of prohibited trailing commas.

    # The following D10* are for undocumented things in a "public module", which scripts count as 
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",

    "EM101", # Raw string in exception
    "EM102", # f string in exception

    "ERA", # Commented out code

    "I001", # Unsorted import. Ruff formatting handles this and is less picky than the lint

    "PLR2004", # Magic values in comparisons

    "PLW2901", # Redefining a loop variable. Eg: for line in sys.stdin: line=line.strip()

    "PTH123", # Checks for uses of the open() builtin instead of Path.open()

    "S607", # Running a command with subprocess without a path (eg: cat instead of /usr/bin/cat)

    "T20",     # Usage of print/pprint

    "TRY002", # raising a base Exception instead of a custom one
    "TRY003", # custom "long" exception messages 
]
